[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "en"

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "de"

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "nl"
    titleAddition = "Modern documentatie-thema"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    titleHome = "Doks thema"
    footer = "Mogelijk gemaakt door <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, en <a href=\"https://getdoks.org/\">Doks</a>"
    alertText = "Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Bekijk Doks v0.2</a>"

[fa]
  languageName = "Persian"
  contentDir = "content/fa"
  weight = 20
  [fa.params]
    rtl = true
    languageISO = "fa"
    titleAddition = "دانشنامه"
    description = "دانشنامه پیشگامان شبکه‌های خردگرا"
    titleHome = "خانه"
    footer = "&copy; پیشگامان شبکه‌های خردگرا"
    alertText = "از اینا DX + UX-updates en meer! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Bekijk Doks v0.2</a>"
    customCSS = ["fa/assets/css/fonts.css"]
    customJS = ["fa/assets/js/moment-jalali.browser.js","fa/assets/js/persian-date.js"]
